sudo: false
language: python
python:
- '3.5'
- '3.6'
install: pip install tox-travis
script: tox
deploy:
  provider: pypi
  user: sayoun
  password:
    secure: oT4sl+uiMT8uu7WO0jBtIFhF2+vQAlntvk03QGjLIk9NWsbO6ssJzZ+93S2AETwyN69jZoI8JhTi1Y7Xzvq3CJYdEJfoUxO6eI5FITTFg/UDHUiBl1/T4dBPrFu4cbZTgFBDmpRXdAz+UdiiJ7rzOzHoT1RpJWYDyfSg3sCMOPlZKrBdNYDkiJ1pVxOW6su/8TudbjxFeOvevXD1gIGzjhN9YrgxsIHREvt/jIOdIuJpt8ugQYuyR7IH3/WuMz7urXMFVRW1mBFpEuOIGtgB87FPX1cANCnCIv8oLwIwFJgkZqAsyWo27fy4wnCr4QelCQbe/6N4fXOsWZw2KsUK/8x2FMUbtS/j4LXkVBE05FxVX3KyiJx3s80KjDbo0v3Y3JDtoo2WDJsN8nN6BUEmWCprvJ4VZU3CvoJDShf7HyqqX16ugYPG5MrI/GjZy6IPvuPeRqVe/kNY8YpMk9b+V73Iysdr/jnnguOJwidmq1B9zTcMCFXnsAr8DphMQLZuca7kon77BIbS4tly7vOa5pEiXcWfIgIgndHIay/TUwaPXmjEoXhkYQ0JwnSyuqD0EsOdzmrnPlCvm+23hNRLC04MO965pMIH7rLmMONZWMCVsf1MUoEZzIBwUaWjsMJzdpiosTDU2NrskVMGnocp3uMjViqrfpBsQQOvxAtx9bE=
  on:
    tags: true
