sudo: false
language: python
python:
- '3.5'
- '3.6'
install: pip install tox-travis
script: tox
deploy:
  provider: pypi
  user: sayoun
  password:
    secure: Dzm/HDNK0a4CuAvMiQ9gFN9UClKb1g0nfh6BiAz0qxQ2vuZ0+m1nXWLGk9x6HQlsfBKmBldW5c1Ha0ux3yNqs8eaq6eEPmfXYzuC2EQQGQnR5bjuHYCwlZSvI5FYUHRKQ5FgbwUXyhXtu2hUBzTJPHZ+H7+CSEV9NXm4ZiY8FUgl4o79S3Chosnl+wUHIkGsTIYcKjuj3rNPnDhFX39MdVIpJasTkSP8HfEgFeil8n/BM00d5izYbAuHQqgupWu2cr7MYvfDJk/X0ilY6/aTjeqLqaRKQdnwuMH1hIHo6vUhv+xTSTdi1tyTrp1REKEhTkonchHdYnsgi/ekS4DCt0pJRfQokY+SxejQv5xann9z/Z9EMkRxU79wamXaZD/zI9G4LTj9P7J15TJHWK2iRHoAwMarJ2rrImpOgqE1jbYLWqmp3oVYu87DgykhZuIMXC9/r3g9SDFephq8ZIBryqRm9kviwTANiAeHUwyGh/zchxmdrbISHDrSw/dRFyUyU0ZoFb/frD4JUumzBUplxB9jbpV6FcS540wAYZs8kl1kYJ7dQ/7XgboiqszlrlYRlkrtJV95FZog8cvrKlY0q0btTKo+CZk+aIwvNeva0klJuN9E1iCd5T2ornXg7pYtfILBQbdlPs+xcBBkbOCSEBTX48qxQUiglOIfzKAoODk=
  on:
    tags: true
